### ISSUE TITLE
style css not being applied

### ISSUE THREAD

**Issue by v-cagome** [Godofbrowser/vuejs-dialog#28]
Added styles below to css files, but being ignored.
Any ideas?

.dg-btn--ok {
     border-color: green;
 }
 
.dg-btn-loader .dg-circle {
    background-color: green;
}

**Comment by Godofbrowser** [comment]
@v-cagome I think this is due to the fact that the styles are injected just before the close of the head tag.

This means that your custom style will probably be above the injected style and it will be overridden.

A quick fix will be to make the custom style important. ie: 
```css
.dg-btn--ok {
border-color: green !important;
}

.dg-btn-loader .dg-circle {
background-color: green !important;
}
```

The best solution will be to make the style injection optional. That way, users can just link the css file in the head tag.
